import type { Metadata } from "next";
import "./globals.css";
import { ChildrenType } from "@/types/types";

export const metadata: Metadata = {
  title: "Tabseer Shop",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: ChildrenType) => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
